include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: false
    omit_local_variable_types: false

formatter:
  page_width: 300
  trailing_commas: preserve
